apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks-demo
spec:
  selector:
    matchLabels:
      app: ctse-assignment-microservices
  template:
    metadata:
      labels:
        app: ctse-assignment-microservices
    spec:
      containers:
        - name: githubactions-aks-demo
          image: nirmith99/ctse-assignment-microservices
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080